# Change these first
owner: Network-For-Gamers # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: NFG
    url: https://networkforgamers.com
    expectedStatusCodes:
      - 200
  - name: NFG CDS
    url: https://cds.networkforgamers.com
    expectedStatusCodes:
      - 200
  - name: NFG Discord
    url: https://discord.networkforgamers.com
    expectedStatusCodes:
      - 200
  - name: NFG Minecraft
    url: https://minecraft.networkforgamers.com
    expectedStatusCodes:
      - 200
  - name: NFG MC
    check: "tcp-ping"
    url: mc.networkforgamers.com
    port: 25565
  - name: NFG Rust
    url: https://rust.networkforgamers.com
    expectedStatusCodes:
      - 200
  - name: SFU
    url: https://serversforyou.com
    expectedStatusCodes:
      - 200
  - name: SFU Discord
    url: https://discord.serversforyou.com
    expectedStatusCodes:
      - 200
  - name: SFU Gaming
    url: https://gaming.serversforyou.com
    expectedStatusCodes:
      - 200
  - name: SFU Web
    url: https://web.serversforyou.com
    expectedStatusCodes:
      - 200
  - name: SFU Node 1
    url: https://node1.serversforyou.com
    expectedStatusCodes:
      - 200
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  theme: dark
  logoUrl: https://avatars.githubusercontent.com/u/74440503?s=400&u=0f5d9aefd0d12b437d633ba23140bdd57e007956&v=4
  name: Networkforgamers
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
